# Generated by Django 4.0.3 on 2022-06-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('units', models.CharField(blank=True, choices=[('кг', 'килограмм'), ('л', 'литр'), ('г', 'грамм'), ('мл', 'миллилитр'), ('шт', 'штука')], max_length=20)),
            ],
        ),
    ]
