# Generated by Django 4.0.3 on 2022-06-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_slug_alter_mealcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='servings',
            field=models.SmallIntegerField(default=None, max_length=3, null=True, verbose_name='Кол-во порций'),
        ),
    ]
