# Generated by Django 4.0.3 on 2022-06-26 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_meal_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='servings',
            field=models.SmallIntegerField(null=True, verbose_name='Кол-во порций'),
        ),
        migrations.AlterField(
            model_name='mealcategory',
            name='name',
            field=models.CharField(max_length=15, unique=True, verbose_name='Категория блюда'),
        ),
        migrations.AlterField(
            model_name='mealcategory',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='mealingredients',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='meals.meal'),
        ),
    ]
