# Generated by Django 4.0.3 on 2022-06-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('meals', '0004_alter_meal_servings_alter_mealcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealingredients',
            unique_together={('ingredient', 'meal')},
        ),
    ]
