# Generated by Django 4.0.3 on 2022-06-19 14:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_slug_alter_mealcategory_slug'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 14, 13, 35, 567310, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='launch_day', to='menu.day')),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch', to='meals.meal', verbose_name='Обед')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_day', to='menu.day')),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner', to='meals.meal', verbose_name='Ужин')),
            ],
        ),
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_day', to='menu.day')),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast', to='meals.meal', verbose_name='Завтрак')),
            ],
        ),
        migrations.AlterField(
            model_name='day',
            name='breakfast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast', to='menu.breakfast'),
        ),
        migrations.AlterField(
            model_name='day',
            name='dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner', to='menu.dinner'),
        ),
        migrations.AlterField(
            model_name='day',
            name='launch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch', to='menu.launch'),
        ),
    ]
