# Generated by Django 4.0.3 on 2022-06-19 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_day_options_alter_day_date_launch_dinner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='day',
        ),
        migrations.RemoveField(
            model_name='dinner',
            name='day',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='day',
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 14, 19, 53, 549370, tzinfo=utc)),
        ),
    ]
