# Generated by Django 4.0.3 on 2022-06-19 20:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_breakfast_day_remove_dinner_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='day',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='day',
            name='launch',
        ),
        migrations.AddField(
            model_name='breakfast',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_breakfast', to='menu.day'),
        ),
        migrations.AddField(
            model_name='dinner',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_dinner', to='menu.day'),
        ),
        migrations.AddField(
            model_name='launch',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_launch', to='menu.day'),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 19, 20, 45, 41, 944913, tzinfo=utc)),
        ),
    ]
